#
# Copyright (c) 2017 PHYTEC Messtechnik GmbH
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the PHYTEC Messtechnik GmbH nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import datetime
import Image, ImageDraw, ImageFont

fontSize = 13
fontFamily = 'FiraCode-Light.otf'
width = 10
height = 16
firstChar = 32
lastChar = 127
numChars = lastChar - firstChar
filePath = 'yafg_glyphs.h'
defineName = 'YAFG_GLYPHS'
structName = 'yafg_pic'
arrayName = 'yafg_glyphs'
companyName = 'PHYTEC Messtechnik GmbH'

header = '/*\n * Copyright (c) ' + str(datetime.datetime.now().year)
header += ' ' + companyName + '\n'
header += ''' *
 * This file was generated from the font "FiraCode" which is licensed
 * under the SIL Open Font License, Version 1.1. The authors of
 * "FiraCode" are:
 *
 * Copyright (c) 2014, Nikita Prokopov http://tonsky.me
 * with Reserved Font Name Fira Code.
 *
 * Copyright (c) 2014, Mozilla Foundation https://mozilla.org/
 * with Reserved Font Name Fira Sans.
 *
 * Copyright (c) 2014, Mozilla Foundation https://mozilla.org/
 * with Reserved Font Name Fira Mono.
 *
 * Copyright (c) 2014, Telefonica S.A.
 */

#ifndef ''' + defineName + '_H\n#define ' + defineName + '_H'
header += '''\n\n/*
 * DO NOT EDIT THIS FILE!
 * Use the Python script to generate this header!
 */\n\n'''
header += '#define ' + defineName + '_FIRST_CHAR  ' + str(firstChar) + '\n'
header += '#define ' + defineName + '_LAST_CHAR   ' + str(lastChar) + '\n\n'
header += 'static struct ' + structName + ' ' + arrayName + '[] = {'

image = Image.new('1', (width*numChars, height), 'white')
draw = ImageDraw.Draw(image)
font = ImageFont.truetype(fontFamily, fontSize)
for c in range(firstChar, lastChar):
	draw.text(((c-firstChar)*width, 0), chr(c), font=font)
image.show()

for c in range(firstChar, lastChar):
	image = Image.new('1', (width, height), 'white')
	draw = ImageDraw.Draw(image)
	font = ImageFont.truetype(fontFamily, fontSize)
	draw.text((0, 0), chr(c), font=font)
	pixel = image.load()

	header += '\n\t{ /* ' + chr(c) + ' */'
	header += '\n\t\t.width = {0}, .height = {1},'.format(width, height)
	header += '\n\t\t.data = {'

	for x in range(width):
		b1 = 0x00
		b2 = 0x00

		for y in range(height):
			if pixel[x, y] < 127:
				if y < 8:
					b1 |= 0x01 << y
				else:
					b2 |= 0x01 << (y - 8)

		header += '\n\t\t\t0x{:02x}, 0x{:02x},'.format(b1, b2)

	header += '\n\t\t}'
	header += '\n\t},'

header += '\n};'
header += '\n\n#endif /* ' + defineName + '_H */\n'

with open(filePath, 'w') as headerFile:
	headerFile.write(header)

print('Generated ' + filePath)
